# Site settings
name: ROBIN的博客
email: luweb@foxmail.com
author: Robin
url: http://luweb.gitee.io
resume_site: http://luweb.gitee.io/me/
github: https://github.com/luoweb/
baseurl: ""  #根目录
description: 坚持 超脱 存在
motto: 坚持 超脱 存在
#motto: 如果生活欺骗了你，不要悲伤，不要哭泣。
banner: Sometimes dream may not come true, but life has become better。
#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
excerpt_separator:  '<!-- more -->' #文章摘要
paginate: 8
paginate_path: "page:num"
plugins: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
github_username: luoweb
highlighter: rouge
markdown: kramdown
FB:
  comments :
    provider : disqus
    disqus :
        short_name : roweb
